"""Compose `.agents/` and CLAUDE.md/AGENTS.md from active stacks.

Strategy:
  - For each stack (in order from workspace.yml), copy its rules/, skills/,
    and workflows/ subtrees into the workspace's `.agents/`. Later stacks
    win on filename collisions, with a recorded warning.
  - Generate CLAUDE.md (canonical) with a header listing the active stacks
    and a preserved <!-- @awac:editable --> block. Mirror to AGENTS.md.

This is intentionally simple for v1. Symlinks are not used to keep behavior
identical on Windows + macOS + Linux.
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

from wsp import __version__ as WSP_VERSION

AGENT_DIRS = ("rules", "skills", "workflows")
EDITABLE_START = "<!-- @awac:editable-start -->"
EDITABLE_END = "<!-- @awac:editable-end -->"
HEADER_START = "<!-- @awac:header-start -->"
HEADER_END = "<!-- @awac:header-end -->"


@dataclass
class ComposeReport:
    workspace: Path
    agent_dirs_written: list[str] = field(default_factory=list)
    file_count: int = 0
    collisions: list[dict[str, str]] = field(default_factory=list)
    canonical: str = ""
    mirrors: list[str] = field(default_factory=list)


def _copy_subtree(src: Path, dest: Path, source_label: str, collisions: list[dict[str, str]]) -> int:
    if not src.exists() or not src.is_dir():
        return 0
    count = 0
    for item in src.rglob("*"):
        if item.is_dir():
            continue
        rel = item.relative_to(src)
        target = dest / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists():
            collisions.append({"file": str((dest.name / rel).as_posix()), "winner": source_label})
        shutil.copy2(item, target)
        count += 1
    return count


def compose_agents(
    workspace_root: Path,
    stacks: list[tuple[str, Path]],
) -> ComposeReport:
    """Copy rules/skills/workflows from each stack into <workspace>/.agents/.

    `stacks` is a list of (label, stack_root_path). Order matters: later wins.
    """
    workspace_root = Path(workspace_root)
    agents_dir = workspace_root / ".agents"
    if agents_dir.exists():
        shutil.rmtree(agents_dir)
    agents_dir.mkdir(parents=True)

    report = ComposeReport(workspace=workspace_root)
    for sub in AGENT_DIRS:
        (agents_dir / sub).mkdir(parents=True, exist_ok=True)
        report.agent_dirs_written.append(sub)

    for label, root in stacks:
        for sub in AGENT_DIRS:
            count = _copy_subtree(root / sub, agents_dir / sub, label, report.collisions)
            report.file_count += count

    return report


def render_agent_file(
    workspace_name: str,
    stacks_summary: list[dict[str, str]],
    editable_block: str | None,
    extras: dict[str, str] | None = None,
) -> str:
    """Build the canonical CLAUDE.md / AGENTS.md content."""
    extras = extras or {}
    lines: list[str] = []
    lines.append(HEADER_START)
    lines.append(f"# Workspace: {workspace_name}")
    lines.append("")
    lines.append(
        "This file is generated by [`wsp`](https://github.com/getGanemo/workspace-cli) "
        f"(v{WSP_VERSION}). Edit only inside the @awac:editable block — everything else "
        "is regenerated by `wsp bootstrap`."
    )
    lines.append("")
    lines.append("## Active stacks")
    lines.append("")
    for s in stacks_summary:
        line = f"- **{s['label']}** — `{s['repo']}@{s['ref']}`"
        if s.get("commit"):
            line += f" (`{s['commit'][:8]}`)"
        lines.append(line)
    lines.append("")
    if extras.get("repos_summary"):
        lines.append("## Cloned product repos")
        lines.append("")
        lines.append(extras["repos_summary"])
        lines.append("")
    lines.append("Agent assets live under `.agents/{rules,skills,workflows}/`.")
    lines.append(HEADER_END)
    lines.append("")
    lines.append(EDITABLE_START)
    if editable_block is None:
        lines.append("<!--")
        lines.append("Hand-authored content for this workspace goes here. `wsp bootstrap`")
        lines.append("preserves anything between the @awac:editable markers.")
        lines.append("-->")
    else:
        lines.append(editable_block.strip("\n"))
    lines.append(EDITABLE_END)
    lines.append("")
    return "\n".join(lines)


def extract_editable_block(text: str) -> str | None:
    if not text:
        return None
    pattern = re.compile(
        re.escape(EDITABLE_START) + r"\n?(.*?)\n?" + re.escape(EDITABLE_END),
        re.DOTALL,
    )
    match = pattern.search(text)
    return match.group(1) if match else None


def write_agent_files(
    workspace_root: Path,
    canonical_name: str,
    mirror_names: Iterable[str],
    workspace_name: str,
    stacks_summary: list[dict[str, str]],
    repos_summary: str | None = None,
) -> tuple[str, list[str]]:
    workspace_root = Path(workspace_root)
    canonical_path = workspace_root / canonical_name
    existing = canonical_path.read_text(encoding="utf-8") if canonical_path.exists() else ""
    editable = extract_editable_block(existing)
    content = render_agent_file(
        workspace_name=workspace_name,
        stacks_summary=stacks_summary,
        editable_block=editable,
        extras={"repos_summary": repos_summary} if repos_summary else None,
    )
    canonical_path.write_text(content, encoding="utf-8")

    mirrors_written: list[str] = []
    for mirror in mirror_names:
        mp = workspace_root / mirror
        mp.write_text(content, encoding="utf-8")
        mirrors_written.append(mirror)
    return canonical_name, mirrors_written
